### ISSUE TITLE
Please use @include 'header' instead of @header (deprecated)

### ISSUE THREAD

**Issue by LucasMW** [scurty-labs/vblog#2]
`v .`

> templates/admin.html:1:1: error: Please use @include 'header' instead of @header (deprecated)
>     1 | @header
>       | ~~~~~~~
>     2 | 
>     3 | @if !app.is_admin

**Comment by scurty-labs** [comment]
Sorry for super late reply. Things have indeed changed in vweb/vlib a lot. I'll get to fixing/updating it as soon as I have the time to do so. Sorry for the super long wait. I plan to add even more basic blogging features as well, but we'll see how my schedule looks.

**Comment by scurty-labs** [comment]
Fixed in latest commit.
